name = "VersionCheck"
uuid = "a637dc6b-bca1-447e-a4fa-35264c9d0580"
authors = ["Adrian Salceanu <e@essenciary.com> and contributors"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
